// availableAirlines.ts

export const availableAirlines = [
  // Middle East & Africa
  { name: 'EgyptAir', code: 'MS', country: 'Egypt', logo: 'https://images.kiwi.com/airlines/64/MS.png' },
  { name: 'Emirates', code: 'EK', country: 'UAE', logo: 'https://images.kiwi.com/airlines/64/EK.png' },
  { name: 'Qatar Airways', code: 'QR', country: 'Qatar', logo: 'https://images.kiwi.com/airlines/64/QR.png' },
  { name: 'Etihad Airways', code: 'EY', country: 'UAE', logo: 'https://images.kiwi.com/airlines/64/EY.png' },
  { name: 'Saudi Airlines', code: 'SV', country: 'Saudi Arabia', logo: 'https://images.kiwi.com/airlines/64/SV.png' },
  { name: 'Flynas', code: 'XY', country: 'Saudi Arabia', logo: 'https://images.kiwi.com/airlines/64/XY.png' },
  { name: 'Air Arabia', code: 'G9', country: 'UAE', logo: 'https://images.kiwi.com/airlines/64/G9.png' },
  { name: 'Flydubai', code: 'FZ', country: 'UAE', logo: 'https://images.kiwi.com/airlines/64/FZ.png' },
  { name: 'Kuwait Airways', code: 'KU', country: 'Kuwait', logo: 'https://images.kiwi.com/airlines/64/KU.png' },
  { name: 'Gulf Air', code: 'GF', country: 'Bahrain', logo: 'https://images.kiwi.com/airlines/64/GF.png' },
  { name: 'Oman Air', code: 'WY', country: 'Oman', logo: 'https://images.kiwi.com/airlines/64/WY.png' },
  { name: 'Middle East Airlines', code: 'ME', country: 'Lebanon', logo: 'https://images.kiwi.com/airlines/64/ME.png' },
  { name: 'Royal Jordanian', code: 'RJ', country: 'Jordan', logo: 'https://images.kiwi.com/airlines/64/RJ.png' },
  { name: 'Iraqi Airways', code: 'IA', country: 'Iraq', logo: 'https://images.kiwi.com/airlines/64/IA.png' },
  { name: 'Fly Baghdad', code: 'IF', country: 'Iraq', logo: 'https://images.kiwi.com/airlines/64/IF.png' },
  { name: 'Ethiopian Airlines', code: 'ET', country: 'Ethiopia', logo: 'https://images.kiwi.com/airlines/64/ET.png' },
  { name: 'Kenya Airways', code: 'KQ', country: 'Kenya', logo: 'https://images.kiwi.com/airlines/64/KQ.png' },
  { name: 'South African Airways', code: 'SA', country: 'South Africa', logo: 'https://images.kiwi.com/airlines/64/SA.png' },
  { name: 'Royal Air Maroc', code: 'AT', country: 'Morocco', logo: 'https://images.kiwi.com/airlines/64/AT.png' },
  { name: 'Air Algerie', code: 'AH', country: 'Algeria', logo: 'https://images.kiwi.com/airlines/64/AH.png' },
  { name: 'Tunisair', code: 'TU', country: 'Tunisia', logo: 'https://images.kiwi.com/airlines/64/TU.png' },
  // Europe
  { name: 'Turkish Airlines', code: 'TK', country: 'Turkey', logo: 'https://images.kiwi.com/airlines/64/TK.png' },
  { name: 'Lufthansa', code: 'LH', country: 'Germany', logo: 'https://images.kiwi.com/airlines/64/LH.png' },
  { name: 'British Airways', code: 'BA', country: 'UK', logo: 'https://images.kiwi.com/airlines/64/BA.png' },
  { name: 'Air France', code: 'AF', country: 'France', logo: 'https://images.kiwi.com/airlines/64/AF.png' },
  { name: 'KLM', code: 'KL', country: 'Netherlands', logo: 'https://images.kiwi.com/airlines/64/KL.png' },
  { name: 'Alitalia', code: 'AZ', country: 'Italy', logo: 'https://images.kiwi.com/airlines/64/AZ.png' },
  { name: 'Iberia', code: 'IB', country: 'Spain', logo: 'https://images.kiwi.com/airlines/64/IB.png' },
  { name: 'Swiss International', code: 'LX', country: 'Switzerland', logo: 'https://images.kiwi.com/airlines/64/LX.png' },
  { name: 'Austrian Airlines', code: 'OS', country: 'Austria', logo: 'https://images.kiwi.com/airlines/64/OS.png' },
  { name: 'Brussels Airlines', code: 'SN', country: 'Belgium', logo: 'https://images.kiwi.com/airlines/64/SN.png' },
  { name: 'Scandinavian Airlines', code: 'SK', country: 'Sweden', logo: 'https://images.kiwi.com/airlines/64/SK.png' },
  { name: 'Finnair', code: 'AY', country: 'Finland', logo: 'https://images.kiwi.com/airlines/64/AY.png' },
  { name: 'Aeroflot', code: 'SU', country: 'Russia', logo: 'https://images.kiwi.com/airlines/64/SU.png' },
  { name: 'LOT Polish Airlines', code: 'LO', country: 'Poland', logo: 'https://images.kiwi.com/airlines/64/LO.png' },
  { name: 'Czech Airlines', code: 'OK', country: 'Czech Republic', logo: 'https://images.kiwi.com/airlines/64/OK.png' },
  { name: 'Air Serbia', code: 'JU', country: 'Serbia', logo: 'https://images.kiwi.com/airlines/64/JU.png' },
  { name: 'TAP Air Portugal', code: 'TP', country: 'Portugal', logo: 'https://images.kiwi.com/airlines/64/TP.png' },
  { name: 'Aegean Airlines', code: 'A3', country: 'Greece', logo: 'https://images.kiwi.com/airlines/64/A3.png' },
  { name: 'Ryanair', code: 'FR', country: 'Ireland', logo: 'https://images.kiwi.com/airlines/64/FR.png' },
  { name: 'EasyJet', code: 'U2', country: 'UK', logo: 'https://images.kiwi.com/airlines/64/U2.png' },
  { name: 'Wizz Air', code: 'W6', country: 'Hungary', logo: 'https://images.kiwi.com/airlines/64/W6.png' },
  { name: 'Norwegian Air', code: 'DY', country: 'Norway', logo: 'https://images.kiwi.com/airlines/64/DY.png' },
  { name: 'Vueling', code: 'VY', country: 'Spain', logo: 'https://images.kiwi.com/airlines/64/VY.png' },
  { name: 'Pegasus Airlines', code: 'PC', country: 'Turkey', logo: 'https://images.kiwi.com/airlines/64/PC.png' },
  // North America
  { name: 'American Airlines', code: 'AA', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/AA.png' },
  { name: 'Delta Air Lines', code: 'DL', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/DL.png' },
  { name: 'United Airlines', code: 'UA', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/UA.png' },
  { name: 'Southwest Airlines', code: 'WN', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/WN.png' },
  { name: 'JetBlue Airways', code: 'B6', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/B6.png' },
  { name: 'Alaska Airlines', code: 'AS', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/AS.png' },
  { name: 'Spirit Airlines', code: 'NK', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/NK.png' },
  { name: 'Frontier Airlines', code: 'F9', country: 'USA', logo: 'https://images.kiwi.com/airlines/64/F9.png' },
  { name: 'Air Canada', code: 'AC', country: 'Canada', logo: 'https://images.kiwi.com/airlines/64/AC.png' },
  { name: 'WestJet', code: 'WS', country: 'Canada', logo: 'https://images.kiwi.com/airlines/64/WS.png' },
  { name: 'Aeromexico', code: 'AM', country: 'Mexico', logo: 'https://images.kiwi.com/airlines/64/AM.png' },
  { name: 'Volaris', code: 'Y4', country: 'Mexico', logo: 'https://images.kiwi.com/airlines/64/Y4.png' },
  // Asia Pacific
  { name: 'Singapore Airlines', code: 'SQ', country: 'Singapore', logo: 'https://images.kiwi.com/airlines/64/SQ.png' },
  { name: 'Cathay Pacific', code: 'CX', country: 'Hong Kong', logo: 'https://images.kiwi.com/airlines/64/CX.png' },
  { name: 'Japan Airlines', code: 'JL', country: 'Japan', logo: 'https://images.kiwi.com/airlines/64/JL.png' },
  { name: 'All Nippon Airways', code: 'NH', country: 'Japan', logo: 'https://images.kiwi.com/airlines/64/NH.png' },
  { name: 'Korean Air', code: 'KE', country: 'South Korea', logo: 'https://images.kiwi.com/airlines/64/KE.png' },
  { name: 'Asiana Airlines', code: 'OZ', country: 'South Korea', logo: 'https://images.kiwi.com/airlines/64/OZ.png' },
  { name: 'China Southern', code: 'CZ', country: 'China', logo: 'https://images.kiwi.com/airlines/64/CZ.png' },
  { name: 'China Eastern', code: 'MU', country: 'China', logo: 'https://images.kiwi.com/airlines/64/MU.png' },
  { name: 'Air China', code: 'CA', country: 'China', logo: 'https://images.kiwi.com/airlines/64/CA.png' },
  { name: 'Hainan Airlines', code: 'HU', country: 'China', logo: 'https://images.kiwi.com/airlines/64/HU.png' },
  { name: 'Thai Airways', code: 'TG', country: 'Thailand', logo: 'https://images.kiwi.com/airlines/64/TG.png' },
  { name: 'Malaysia Airlines', code: 'MH', country: 'Malaysia', logo: 'https://images.kiwi.com/airlines/64/MH.png' },
  { name: 'Garuda Indonesia', code: 'GA', country: 'Indonesia', logo: 'https://images.kiwi.com/airlines/64/GA.png' },
  { name: 'Philippine Airlines', code: 'PR', country: 'Philippines', logo: 'https://images.kiwi.com/airlines/64/PR.png' },
  { name: 'Vietnam Airlines', code: 'VN', country: 'Vietnam', logo: 'https://images.kiwi.com/airlines/64/VN.png' },
  { name: 'Air India', code: 'AI', country: 'India', logo: 'https://images.kiwi.com/airlines/64/AI.png' },
  { name: 'IndiGo', code: '6E', country: 'India', logo: 'https://images.kiwi.com/airlines/64/6E.png' },
  { name: 'SpiceJet', code: 'SG', country: 'India', logo: 'https://images.kiwi.com/airlines/64/SG.png' },
  { name: 'Pakistan International', code: 'PK', country: 'Pakistan', logo: 'https://images.kiwi.com/airlines/64/PK.png' },
  { name: 'Qantas', code: 'QF', country: 'Australia', logo: 'https://images.kiwi.com/airlines/64/QF.png' },
  { name: 'Air New Zealand', code: 'NZ', country: 'New Zealand', logo: 'https://images.kiwi.com/airlines/64/NZ.png' },
  { name: 'AirAsia', code: 'AK', country: 'Malaysia', logo: 'https://images.kiwi.com/airlines/64/AK.png' },
  { name: 'Cebu Pacific', code: '5J', country: 'Philippines', logo: 'https://images.kiwi.com/airlines/64/5J.png' },
  { name: 'Jetstar', code: 'JQ', country: 'Australia', logo: 'https://images.kiwi.com/airlines/64/JQ.png' },
  { name: 'Scoot', code: 'TR', country: 'Singapore', logo: 'https://images.kiwi.com/airlines/64/TR.png' },
  // South America
  { name: 'LATAM Airlines', code: 'LA', country: 'Chile', logo: 'https://images.kiwi.com/airlines/64/LA.png' },
  { name: 'Avianca', code: 'AV', country: 'Colombia', logo: 'https://images.kiwi.com/airlines/64/AV.png' },
  { name: 'Copa Airlines', code: 'CM', country: 'Panama', logo: 'https://images.kiwi.com/airlines/64/CM.png' },
  { name: 'Azul Brazilian', code: 'AD', country: 'Brazil', logo: 'https://images.kiwi.com/airlines/64/AD.png' },
  { name: 'GOL Linhas', code: 'G3', country: 'Brazil', logo: 'https://images.kiwi.com/airlines/64/G3.png' },
  { name: 'Aerolineas Argentinas', code: 'AR', country: 'Argentina', logo: 'https://images.kiwi.com/airlines/64/AR.png' },
];