// countriesAndAirports.tsx

export const countriesAndAirports = [
  // Middle East
  { country: 'Egypt', airports: [{ code: 'CAI', city: 'Cairo' }, { code: 'SSH', city: 'Sharm El Sheikh' }, { code: 'HRG', city: 'Hurghada' }, { code: 'LXR', city: 'Luxor' }, { code: 'ASW', city: 'Aswan' }, { code: 'ALY', city: 'Alexandria' }] },
  { country: 'UAE', airports: [{ code: 'DXB', city: 'Dubai' }, { code: 'AUH', city: 'Abu Dhabi' }, { code: 'SHJ', city: 'Sharjah' }] },
  { country: 'Saudi Arabia', airports: [{ code: 'JED', city: 'Jeddah' }, { code: 'RUH', city: 'Riyadh' }, { code: 'DMM', city: 'Dammam' }, { code: 'MED', city: 'Medina' }] },
  { country: 'Qatar', airports: [{ code: 'DOH', city: 'Doha' }] },
  { country: 'Kuwait', airports: [{ code: 'KWI', city: 'Kuwait City' }] },
  { country: 'Iraq', airports: [{ code: 'BGW', city: 'Baghdad' }, { code: 'BSR', city: 'Basra' }, { code: 'EBL', city: 'Erbil' }] },
  { country: 'Oman', airports: [{ code: 'MCT', city: 'Muscat' }, { code: 'SLL', city: 'Salalah' }] },
  { country: 'Bahrain', airports: [{ code: 'BAH', city: 'Manama' }] },
  { country: 'Jordan', airports: [{ code: 'AMM', city: 'Amman' }, { code: 'AQJ', city: 'Aqaba' }] },
  { country: 'Lebanon', airports: [{ code: 'BEY', city: 'Beirut' }] },
  { country: 'Syria', airports: [{ code: 'DAM', city: 'Damascus' }] },
  { country: 'Yemen', airports: [{ code: 'SAH', city: 'Sanaa' }] },
  { country: 'Iran', airports: [{ code: 'THR', city: 'Tehran' }, { code: 'IKA', city: 'Tehran Imam Khomeini' }] },
  { country: 'Israel', airports: [{ code: 'TLV', city: 'Tel Aviv' }] },
  { country: 'Palestine', airports: [{ code: 'GZA', city: 'Gaza' }] },
  // Europe
  { country: 'UK', airports: [{ code: 'LHR', city: 'London Heathrow' }, { code: 'LGW', city: 'London Gatwick' }, { code: 'MAN', city: 'Manchester' }, { code: 'EDI', city: 'Edinburgh' }, { code: 'BHX', city: 'Birmingham' }] },
  { country: 'France', airports: [{ code: 'CDG', city: 'Paris CDG' }, { code: 'ORY', city: 'Paris Orly' }, { code: 'NCE', city: 'Nice' }, { code: 'LYS', city: 'Lyon' }, { code: 'MRS', city: 'Marseille' }] },
  { country: 'Germany', airports: [{ code: 'FRA', city: 'Frankfurt' }, { code: 'MUC', city: 'Munich' }, { code: 'BER', city: 'Berlin' }, { code: 'DUS', city: 'Düsseldorf' }, { code: 'HAM', city: 'Hamburg' }] },
  { country: 'Italy', airports: [{ code: 'FCO', city: 'Rome Fiumicino' }, { code: 'MXP', city: 'Milan Malpensa' }, { code: 'VCE', city: 'Venice' }, { code: 'NAP', city: 'Naples' }, { code: 'FLR', city: 'Florence' }] },
  { country: 'Spain', airports: [{ code: 'MAD', city: 'Madrid' }, { code: 'BCN', city: 'Barcelona' }, { code: 'AGP', city: 'Malaga' }, { code: 'SVQ', city: 'Seville' }, { code: 'PMI', city: 'Palma Mallorca' }] },
  { country: 'Netherlands', airports: [{ code: 'AMS', city: 'Amsterdam' }] },
  { country: 'Belgium', airports: [{ code: 'BRU', city: 'Brussels' }] },
  { country: 'Switzerland', airports: [{ code: 'ZRH', city: 'Zurich' }, { code: 'GVA', city: 'Geneva' }] },
  { country: 'Austria', airports: [{ code: 'VIE', city: 'Vienna' }] },
  { country: 'Greece', airports: [{ code: 'ATH', city: 'Athens' }, { code: 'HER', city: 'Heraklion' }, { code: 'SKG', city: 'Thessaloniki' }] },
  { country: 'Turkey', airports: [{ code: 'IST', city: 'Istanbul' }, { code: 'SAW', city: 'Istanbul Sabiha' }, { code: 'AYT', city: 'Antalya' }, { code: 'ESB', city: 'Ankara' }, { code: 'IZM', city: 'Izmir' }] },
  { country: 'Portugal', airports: [{ code: 'LIS', city: 'Lisbon' }, { code: 'OPO', city: 'Porto' }, { code: 'FAO', city: 'Faro' }] },
  { country: 'Poland', airports: [{ code: 'WAW', city: 'Warsaw' }, { code: 'KRK', city: 'Krakow' }] },
  { country: 'Czech Republic', airports: [{ code: 'PRG', city: 'Prague' }] },
  { country: 'Hungary', airports: [{ code: 'BUD', city: 'Budapest' }] },
  { country: 'Romania', airports: [{ code: 'OTP', city: 'Bucharest' }] },
  { country: 'Ireland', airports: [{ code: 'DUB', city: 'Dublin' }] },
  { country: 'Sweden', airports: [{ code: 'ARN', city: 'Stockholm' }, { code: 'GOT', city: 'Gothenburg' }] },
  { country: 'Norway', airports: [{ code: 'OSL', city: 'Oslo' }] },
  { country: 'Denmark', airports: [{ code: 'CPH', city: 'Copenhagen' }] },
  { country: 'Finland', airports: [{ code: 'HEL', city: 'Helsinki' }] },
  { country: 'Russia', airports: [{ code: 'SVO', city: 'Moscow Sheremetyevo' }, { code: 'DME', city: 'Moscow Domodedovo' }, { code: 'LED', city: 'St Petersburg' }] },
  { country: 'Ukraine', airports: [{ code: 'KBP', city: 'Kyiv' }] },
  // Asia
  { country: 'China', airports: [{ code: 'PEK', city: 'Beijing' }, { code: 'PVG', city: 'Shanghai Pudong' }, { code: 'CAN', city: 'Guangzhou' }, { code: 'HKG', city: 'Hong Kong' }, { code: 'SZX', city: 'Shenzhen' }] },
  { country: 'Japan', airports: [{ code: 'NRT', city: 'Tokyo Narita' }, { code: 'HND', city: 'Tokyo Haneda' }, { code: 'KIX', city: 'Osaka' }, { code: 'NGO', city: 'Nagoya' }] },
  { country: 'South Korea', airports: [{ code: 'ICN', city: 'Seoul Incheon' }, { code: 'GMP', city: 'Seoul Gimpo' }, { code: 'PUS', city: 'Busan' }] },
  { country: 'India', airports: [{ code: 'DEL', city: 'Delhi' }, { code: 'BOM', city: 'Mumbai' }, { code: 'BLR', city: 'Bangalore' }, { code: 'MAA', city: 'Chennai' }, { code: 'CCU', city: 'Kolkata' }] },
  { country: 'Pakistan', airports: [{ code: 'KHI', city: 'Karachi' }, { code: 'LHE', city: 'Lahore' }, { code: 'ISB', city: 'Islamabad' }] },
  { country: 'Bangladesh', airports: [{ code: 'DAC', city: 'Dhaka' }] },
  { country: 'Sri Lanka', airports: [{ code: 'CMB', city: 'Colombo' }] },
  { country: 'Nepal', airports: [{ code: 'KTM', city: 'Kathmandu' }] },
  { country: 'Thailand', airports: [{ code: 'BKK', city: 'Bangkok Suvarnabhumi' }, { code: 'DMK', city: 'Bangkok Don Mueang' }, { code: 'HKT', city: 'Phuket' }, { code: 'CNX', city: 'Chiang Mai' }] },
  { country: 'Vietnam', airports: [{ code: 'SGN', city: 'Ho Chi Minh' }, { code: 'HAN', city: 'Hanoi' }] },
  { country: 'Singapore', airports: [{ code: 'SIN', city: 'Singapore' }] },
  { country: 'Malaysia', airports: [{ code: 'KUL', city: 'Kuala Lumpur' }, { code: 'PEN', city: 'Penang' }] },
  { country: 'Indonesia', airports: [{ code: 'CGK', city: 'Jakarta' }, { code: 'DPS', city: 'Bali' }, { code: 'SUB', city: 'Surabaya' }] },
  { country: 'Philippines', airports: [{ code: 'MNL', city: 'Manila' }, { code: 'CEB', city: 'Cebu' }] },
  { country: 'Cambodia', airports: [{ code: 'PNH', city: 'Phnom Penh' }, { code: 'REP', city: 'Siem Reap' }] },
  { country: 'Myanmar', airports: [{ code: 'RGN', city: 'Yangon' }] },
  { country: 'Laos', airports: [{ code: 'VTE', city: 'Vientiane' }] },
  { country: 'Azerbaijan', airports: [{ code: 'GYD', city: 'Baku' }] },
  { country: 'Georgia', airports: [{ code: 'TBS', city: 'Tbilisi' }] },
  { country: 'Armenia', airports: [{ code: 'EVN', city: 'Yerevan' }] },
  { country: 'Kazakhstan', airports: [{ code: 'ALA', city: 'Almaty' }] },
  { country: 'Uzbekistan', airports: [{ code: 'TAS', city: 'Tashkent' }] },
  // Americas
  { country: 'USA', airports: [{ code: 'JFK', city: 'New York JFK' }, { code: 'LAX', city: 'Los Angeles' }, { code: 'ORD', city: 'Chicago' }, { code: 'MIA', city: 'Miami' }, { code: 'ATL', city: 'Atlanta' }, { code: 'SFO', city: 'San Francisco' }, { code: 'DFW', city: 'Dallas' }, { code: 'LAS', city: 'Las Vegas' }] },
  { country: 'Canada', airports: [{ code: 'YYZ', city: 'Toronto' }, { code: 'YVR', city: 'Vancouver' }, { code: 'YUL', city: 'Montreal' }, { code: 'YYC', city: 'Calgary' }] },
  { country: 'Mexico', airports: [{ code: 'MEX', city: 'Mexico City' }, { code: 'CUN', city: 'Cancun' }, { code: 'GDL', city: 'Guadalajara' }] },
  { country: 'Brazil', airports: [{ code: 'GRU', city: 'São Paulo' }, { code: 'GIG', city: 'Rio de Janeiro' }, { code: 'BSB', city: 'Brasilia' }] },
  { country: 'Argentina', airports: [{ code: 'EZE', city: 'Buenos Aires' }] },
  { country: 'Chile', airports: [{ code: 'SCL', city: 'Santiago' }] },
  { country: 'Colombia', airports: [{ code: 'BOG', city: 'Bogota' }, { code: 'MDE', city: 'Medellin' }] },
  { country: 'Peru', airports: [{ code: 'LIM', city: 'Lima' }] },
  { country: 'Venezuela', airports: [{ code: 'CCS', city: 'Caracas' }] },
  { country: 'Ecuador', airports: [{ code: 'UIO', city: 'Quito' }] },
  { country: 'Panama', airports: [{ code: 'PTY', city: 'Panama City' }] },
  { country: 'Costa Rica', airports: [{ code: 'SJO', city: 'San Jose' }] },
  { country: 'Cuba', airports: [{ code: 'HAV', city: 'Havana' }] },
  { country: 'Dominican Republic', airports: [{ code: 'SDQ', city: 'Santo Domingo' }, { code: 'PUJ', city: 'Punta Cana' }] },
  { country: 'Jamaica', airports: [{ code: 'KIN', city: 'Kingston' }] },
  // Africa
  { country: 'South Africa', airports: [{ code: 'JNB', city: 'Johannesburg' }, { code: 'CPT', city: 'Cape Town' }, { code: 'DUR', city: 'Durban' }] },
  { country: 'Nigeria', airports: [{ code: 'LOS', city: 'Lagos' }, { code: 'ABV', city: 'Abuja' }] },
  { country: 'Kenya', airports: [{ code: 'NBO', city: 'Nairobi' }] },
  { country: 'Ethiopia', airports: [{ code: 'ADD', city: 'Addis Ababa' }] },
  { country: 'Morocco', airports: [{ code: 'CMN', city: 'Casablanca' }, { code: 'RAK', city: 'Marrakech' }] },
  { country: 'Algeria', airports: [{ code: 'ALG', city: 'Algiers' }] },
  { country: 'Tunisia', airports: [{ code: 'TUN', city: 'Tunis' }] },
  { country: 'Libya', airports: [{ code: 'TIP', city: 'Tripoli' }] },
  { country: 'Ghana', airports: [{ code: 'ACC', city: 'Accra' }] },
  { country: 'Senegal', airports: [{ code: 'DSS', city: 'Dakar' }] },
  { country: 'Ivory Coast', airports: [{ code: 'ABJ', city: 'Abidjan' }] },
  { country: 'Tanzania', airports: [{ code: 'DAR', city: 'Dar es Salaam' }] },
  { country: 'Uganda', airports: [{ code: 'EBB', city: 'Entebbe' }] },
  { country: 'Zimbabwe', airports: [{ code: 'HRE', city: 'Harare' }] },
  { country: 'Zambia', airports: [{ code: 'LUN', city: 'Lusaka' }] },
  { country: 'Mozambique', airports: [{ code: 'MPM', city: 'Maputo' }] },
  { country: 'Botswana', airports: [{ code: 'GBE', city: 'Gaborone' }] },
  { country: 'Namibia', airports: [{ code: 'WDH', city: 'Windhoek' }] },
  { country: 'Angola', airports: [{ code: 'LAD', city: 'Luanda' }] },
  { country: 'Congo', airports: [{ code: 'BZV', city: 'Brazzaville' }] },
  { country: 'Rwanda', airports: [{ code: 'KGL', city: 'Kigali' }] },
  { country: 'Cameroon', airports: [{ code: 'DLA', city: 'Douala' }, { code: 'NSI', city: 'Yaounde' }] },
  { country: 'Mali', airports: [{ code: 'BKO', city: 'Bamako' }] },
  { country: 'Burkina Faso', airports: [{ code: 'OUA', city: 'Ouagadougou' }] },
  { country: 'Niger', airports: [{ code: 'NIM', city: 'Niamey' }] },
  { country: 'Chad', airports: [{ code: 'NDJ', city: 'N\'Djamena' }] },
  { country: 'Sudan', airports: [{ code: 'KRT', city: 'Khartoum' }] },
  { country: 'Mauritius', airports: [{ code: 'MRU', city: 'Port Louis' }] },
  { country: 'Seychelles', airports: [{ code: 'SEZ', city: 'Mahe' }] },
  { country: 'Madagascar', airports: [{ code: 'TNR', city: 'Antananarivo' }] },
  // Oceania
  { country: 'Australia', airports: [{ code: 'SYD', city: 'Sydney' }, { code: 'MEL', city: 'Melbourne' }, { code: 'BNE', city: 'Brisbane' }, { code: 'PER', city: 'Perth' }, { code: 'ADL', city: 'Adelaide' }] },
  { country: 'New Zealand', airports: [{ code: 'AKL', city: 'Auckland' }, { code: 'CHC', city: 'Christchurch' }, { code: 'WLG', city: 'Wellington' }] },
  { country: 'Fiji', airports: [{ code: 'NAN', city: 'Nadi' }] },
  { country: 'Papua New Guinea', airports: [{ code: 'POM', city: 'Port Moresby' }] },
  { country: 'New Caledonia', airports: [{ code: 'NOU', city: 'Noumea' }] },
  { country: 'French Polynesia', airports: [{ code: 'PPT', city: 'Tahiti' }] },
  { country: 'Samoa', airports: [{ code: 'APW', city: 'Apia' }] },
  { country: 'Tonga', airports: [{ code: 'TBU', city: 'Nuku\'alofa' }] },
  { country: 'Vanuatu', airports: [{ code: 'VLI', city: 'Port Vila' }] },
  { country: 'Solomon Islands', airports: [{ code: 'HIR', city: 'Honiara' }] },
  // Additional European Countries
  { country: 'Iceland', airports: [{ code: 'KEF', city: 'Reykjavik' }] },
  { country: 'Croatia', airports: [{ code: 'ZAG', city: 'Zagreb' }, { code: 'DBV', city: 'Dubrovnik' }] },
  { country: 'Serbia', airports: [{ code: 'BEG', city: 'Belgrade' }] },
  { country: 'Bulgaria', airports: [{ code: 'SOF', city: 'Sofia' }] },
  { country: 'Slovenia', airports: [{ code: 'LJU', city: 'Ljubljana' }] },
  { country: 'Slovakia', airports: [{ code: 'BTS', city: 'Bratislava' }] },
  { country: 'Estonia', airports: [{ code: 'TLL', city: 'Tallinn' }] },
  { country: 'Latvia', airports: [{ code: 'RIX', city: 'Riga' }] },
  { country: 'Lithuania', airports: [{ code: 'VNO', city: 'Vilnius' }] },
  { country: 'Bosnia', airports: [{ code: 'SJJ', city: 'Sarajevo' }] },
  { country: 'North Macedonia', airports: [{ code: 'SKP', city: 'Skopje' }] },
  { country: 'Albania', airports: [{ code: 'TIA', city: 'Tirana' }] },
  { country: 'Montenegro', airports: [{ code: 'TGD', city: 'Podgorica' }] },
  { country: 'Cyprus', airports: [{ code: 'LCA', city: 'Larnaca' }, { code: 'PFO', city: 'Paphos' }] },
  { country: 'Malta', airports: [{ code: 'MLA', city: 'Malta' }] },
  { country: 'Luxembourg', airports: [{ code: 'LUX', city: 'Luxembourg' }] },
  { country: 'Belarus', airports: [{ code: 'MSQ', city: 'Minsk' }] },
  { country: 'Moldova', airports: [{ code: 'KIV', city: 'Chisinau' }] },
  // Additional Asian Countries
  { country: 'Mongolia', airports: [{ code: 'ULN', city: 'Ulaanbaatar' }] },
  { country: 'Bhutan', airports: [{ code: 'PBH', city: 'Paro' }] },
  { country: 'Maldives', airports: [{ code: 'MLE', city: 'Male' }] },
  { country: 'Brunei', airports: [{ code: 'BWN', city: 'Bandar Seri Begawan' }] },
  { country: 'Timor-Leste', airports: [{ code: 'DIL', city: 'Dili' }] },
  { country: 'Afghanistan', airports: [{ code: 'KBL', city: 'Kabul' }] },
  { country: 'Turkmenistan', airports: [{ code: 'ASB', city: 'Ashgabat' }] },
  { country: 'Tajikistan', airports: [{ code: 'DYU', city: 'Dushanbe' }] },
  { country: 'Kyrgyzstan', airports: [{ code: 'FRU', city: 'Bishkek' }] },
  { country: 'Taiwan', airports: [{ code: 'TPE', city: 'Taipei' }] },
  { country: 'Hong Kong', airports: [{ code: 'HKG', city: 'Hong Kong' }] },
  { country: 'Macau', airports: [{ code: 'MFM', city: 'Macau' }] },
  // Additional American Countries
  { country: 'Uruguay', airports: [{ code: 'MVD', city: 'Montevideo' }] },
  { country: 'Paraguay', airports: [{ code: 'ASU', city: 'Asuncion' }] },
  { country: 'Bolivia', airports: [{ code: 'LPB', city: 'La Paz' }] },
  { country: 'Guatemala', airports: [{ code: 'GUA', city: 'Guatemala City' }] },
  { country: 'Honduras', airports: [{ code: 'SAP', city: 'San Pedro Sula' }] },
  { country: 'Nicaragua', airports: [{ code: 'MGA', city: 'Managua' }] },
  { country: 'El Salvador', airports: [{ code: 'SAL', city: 'San Salvador' }] },
  { country: 'Belize', airports: [{ code: 'BZE', city: 'Belize City' }] },
  { country: 'Guyana', airports: [{ code: 'GEO', city: 'Georgetown' }] },
  { country: 'Suriname', airports: [{ code: 'PBM', city: 'Paramaribo' }] },
  { country: 'French Guiana', airports: [{ code: 'CAY', city: 'Cayenne' }] },
  { country: 'Trinidad and Tobago', airports: [{ code: 'POS', city: 'Port of Spain' }] },
  { country: 'Barbados', airports: [{ code: 'BGI', city: 'Bridgetown' }] },
  { country: 'Bahamas', airports: [{ code: 'NAS', city: 'Nassau' }] },
  { country: 'Haiti', airports: [{ code: 'PAP', city: 'Port-au-Prince' }] },
  { country: 'Puerto Rico', airports: [{ code: 'SJU', city: 'San Juan' }] },
  { country: 'Aruba', airports: [{ code: 'AUA', city: 'Aruba' }] },
  { country: 'Curacao', airports: [{ code: 'CUR', city: 'Willemstad' }] },
];