// countriesAndAirports.ts

export const countriesAndAirports = [
  // Middle East
  { country: 'Egypt', flag: '🇪🇬', airports: [{ code: 'CAI', city: 'Cairo' }, { code: 'SSH', city: 'Sharm El Sheikh' }, { code: 'HRG', city: 'Hurghada' }, { code: 'LXR', city: 'Luxor' }, { code: 'ASW', city: 'Aswan' }, { code: 'ALY', city: 'Alexandria' }] },
  { country: 'UAE', flag: '🇦🇪', airports: [{ code: 'DXB', city: 'Dubai' }, { code: 'AUH', city: 'Abu Dhabi' }, { code: 'SHJ', city: 'Sharjah' }] },
  { country: 'Saudi Arabia', flag: '🇸🇦', airports: [{ code: 'JED', city: 'Jeddah' }, { code: 'RUH', city: 'Riyadh' }, { code: 'DMM', city: 'Dammam' }, { code: 'MED', city: 'Medina' }] },
  { country: 'Qatar', flag: '🇶🇦', airports: [{ code: 'DOH', city: 'Doha' }] },
  { country: 'Kuwait', flag: '🇰🇼', airports: [{ code: 'KWI', city: 'Kuwait City' }] },
  { country: 'Iraq', flag: '🇮🇶', airports: [{ code: 'BGW', city: 'Baghdad' }, { code: 'BSR', city: 'Basra' }, { code: 'EBL', city: 'Erbil' }] },
  { country: 'Oman', flag: '🇴🇲', airports: [{ code: 'MCT', city: 'Muscat' }, { code: 'SLL', city: 'Salalah' }] },
  { country: 'Bahrain', flag: '🇧🇭', airports: [{ code: 'BAH', city: 'Manama' }] },
  { country: 'Jordan', flag: '🇯🇴', airports: [{ code: 'AMM', city: 'Amman' }, { code: 'AQJ', city: 'Aqaba' }] },
  { country: 'Lebanon', flag: '🇱🇧', airports: [{ code: 'BEY', city: 'Beirut' }] },
  { country: 'Syria', flag: '🇸🇾', airports: [{ code: 'DAM', city: 'Damascus' }] },
  { country: 'Yemen', flag: '🇾🇪', airports: [{ code: 'SAH', city: 'Sanaa' }] },
  { country: 'Iran', flag: '🇮🇷', airports: [{ code: 'THR', city: 'Tehran' }, { code: 'IKA', city: 'Tehran Imam Khomeini' }] },
  { country: 'Israel', flag: '🇮🇱', airports: [{ code: 'TLV', city: 'Tel Aviv' }] },
  { country: 'Palestine', flag: '🇵🇸', airports: [{ code: 'GZA', city: 'Gaza' }] },
  // Europe
  { country: 'UK', flag: '🇬🇧', airports: [{ code: 'LHR', city: 'London Heathrow' }, { code: 'LGW', city: 'London Gatwick' }, { code: 'MAN', city: 'Manchester' }, { code: 'EDI', city: 'Edinburgh' }, { code: 'BHX', city: 'Birmingham' }] },
  { country: 'France', flag: '🇫🇷', airports: [{ code: 'CDG', city: 'Paris CDG' }, { code: 'ORY', city: 'Paris Orly' }, { code: 'NCE', city: 'Nice' }, { code: 'LYS', city: 'Lyon' }, { code: 'MRS', city: 'Marseille' }] },
  { country: 'Germany', flag: '🇩🇪', airports: [{ code: 'FRA', city: 'Frankfurt' }, { code: 'MUC', city: 'Munich' }, { code: 'BER', city: 'Berlin' }, { code: 'DUS', city: 'Düsseldorf' }, { code: 'HAM', city: 'Hamburg' }] },
  { country: 'Italy', flag: '🇮🇹', airports: [{ code: 'FCO', city: 'Rome Fiumicino' }, { code: 'MXP', city: 'Milan Malpensa' }, { code: 'VCE', city: 'Venice' }, { code: 'NAP', city: 'Naples' }, { code: 'FLR', city: 'Florence' }] },
  { country: 'Spain', flag: '🇪🇸', airports: [{ code: 'MAD', city: 'Madrid' }, { code: 'BCN', city: 'Barcelona' }, { code: 'AGP', city: 'Malaga' }, { code: 'SVQ', city: 'Seville' }, { code: 'PMI', city: 'Palma Mallorca' }] },
  { country: 'Netherlands', flag: '🇳🇱', airports: [{ code: 'AMS', city: 'Amsterdam' }] },
  { country: 'Belgium', flag: '🇧🇪', airports: [{ code: 'BRU', city: 'Brussels' }] },
  { country: 'Switzerland', flag: '🇨🇭', airports: [{ code: 'ZRH', city: 'Zurich' }, { code: 'GVA', city: 'Geneva' }] },
  { country: 'Austria', flag: '🇦🇹', airports: [{ code: 'VIE', city: 'Vienna' }] },
  { country: 'Greece', flag: '🇬🇷', airports: [{ code: 'ATH', city: 'Athens' }, { code: 'HER', city: 'Heraklion' }, { code: 'SKG', city: 'Thessaloniki' }] },
  { country: 'Turkey', flag: '🇹🇷', airports: [{ code: 'IST', city: 'Istanbul' }, { code: 'SAW', city: 'Istanbul Sabiha' }, { code: 'AYT', city: 'Antalya' }, { code: 'ESB', city: 'Ankara' }, { code: 'IZM', city: 'Izmir' }] },
  { country: 'Portugal', flag: '🇵🇹', airports: [{ code: 'LIS', city: 'Lisbon' }, { code: 'OPO', city: 'Porto' }, { code: 'FAO', city: 'Faro' }] },
  { country: 'Poland', flag: '🇵🇱', airports: [{ code: 'WAW', city: 'Warsaw' }, { code: 'KRK', city: 'Krakow' }] },
  { country: 'Czech Republic', flag: '🇨🇿', airports: [{ code: 'PRG', city: 'Prague' }] },
  { country: 'Hungary', flag: '🇭🇺', airports: [{ code: 'BUD', city: 'Budapest' }] },
  { country: 'Romania', flag: '🇷🇴', airports: [{ code: 'OTP', city: 'Bucharest' }] },
  { country: 'Ireland', flag: '🇮🇪', airports: [{ code: 'DUB', city: 'Dublin' }] },
  { country: 'Sweden', flag: '🇸🇪', airports: [{ code: 'ARN', city: 'Stockholm' }, { code: 'GOT', city: 'Gothenburg' }] },
  { country: 'Norway', flag: '🇳🇴', airports: [{ code: 'OSL', city: 'Oslo' }] },
  { country: 'Denmark', flag: '🇩🇰', airports: [{ code: 'CPH', city: 'Copenhagen' }] },
  { country: 'Finland', flag: '🇫🇮', airports: [{ code: 'HEL', city: 'Helsinki' }] },
  { country: 'Russia', flag: '🇷🇺', airports: [{ code: 'SVO', city: 'Moscow Sheremetyevo' }, { code: 'DME', city: 'Moscow Domodedovo' }, { code: 'LED', city: 'St Petersburg' }] },
  { country: 'Ukraine', flag: '🇺🇦', airports: [{ code: 'KBP', city: 'Kyiv' }] },
  // Asia
  { country: 'China', flag: '🇨🇳', airports: [{ code: 'PEK', city: 'Beijing' }, { code: 'PVG', city: 'Shanghai Pudong' }, { code: 'CAN', city: 'Guangzhou' }, { code: 'HKG', city: 'Hong Kong' }, { code: 'SZX', city: 'Shenzhen' }] },
  { country: 'Japan', flag: '🇯🇵', airports: [{ code: 'NRT', city: 'Tokyo Narita' }, { code: 'HND', city: 'Tokyo Haneda' }, { code: 'KIX', city: 'Osaka' }, { code: 'NGO', city: 'Nagoya' }] },
  { country: 'South Korea', flag: '🇰🇷', airports: [{ code: 'ICN', city: 'Seoul Incheon' }, { code: 'GMP', city: 'Seoul Gimpo' }, { code: 'PUS', city: 'Busan' }] },
  { country: 'India', flag: '🇮🇳', airports: [{ code: 'DEL', city: 'Delhi' }, { code: 'BOM', city: 'Mumbai' }, { code: 'BLR', city: 'Bangalore' }, { code: 'MAA', city: 'Chennai' }, { code: 'CCU', city: 'Kolkata' }] },
  { country: 'Pakistan', flag: '🇵🇰', airports: [{ code: 'KHI', city: 'Karachi' }, { code: 'LHE', city: 'Lahore' }, { code: 'ISB', city: 'Islamabad' }] },
  { country: 'Bangladesh', flag: '🇧🇩', airports: [{ code: 'DAC', city: 'Dhaka' }] },
  { country: 'Sri Lanka', flag: '🇱🇰', airports: [{ code: 'CMB', city: 'Colombo' }] },
  { country: 'Nepal', flag: '🇳🇵', airports: [{ code: 'KTM', city: 'Kathmandu' }] },
  { country: 'Thailand', flag: '🇹🇭', airports: [{ code: 'BKK', city: 'Bangkok Suvarnabhumi' }, { code: 'DMK', city: 'Bangkok Don Mueang' }, { code: 'HKT', city: 'Phuket' }, { code: 'CNX', city: 'Chiang Mai' }] },
  { country: 'Vietnam', flag: '🇻🇳', airports: [{ code: 'SGN', city: 'Ho Chi Minh' }, { code: 'HAN', city: 'Hanoi' }] },
  { country: 'Singapore', flag: '🇸🇬', airports: [{ code: 'SIN', city: 'Singapore' }] },
  { country: 'Malaysia', flag: '🇲🇾', airports: [{ code: 'KUL', city: 'Kuala Lumpur' }, { code: 'PEN', city: 'Penang' }] },
  { country: 'Indonesia', flag: '🇮🇩', airports: [{ code: 'CGK', city: 'Jakarta' }, { code: 'DPS', city: 'Bali' }, { code: 'SUB', city: 'Surabaya' }] },
  { country: 'Philippines', flag: '🇵🇭', airports: [{ code: 'MNL', city: 'Manila' }, { code: 'CEB', city: 'Cebu' }] },
  { country: 'Cambodia', flag: '🇰🇭', airports: [{ code: 'PNH', city: 'Phnom Penh' }, { code: 'REP', city: 'Siem Reap' }] },
  { country: 'Myanmar', flag: '🇲🇲', airports: [{ code: 'RGN', city: 'Yangon' }] },
  { country: 'Laos', flag: '🇱🇦', airports: [{ code: 'VTE', city: 'Vientiane' }] },
  { country: 'Azerbaijan', flag: '🇦🇿', airports: [{ code: 'GYD', city: 'Baku' }] },
  { country: 'Georgia', flag: '🇬🇪', airports: [{ code: 'TBS', city: 'Tbilisi' }] },
  { country: 'Armenia', flag: '🇦🇲', airports: [{ code: 'EVN', city: 'Yerevan' }] },
  { country: 'Kazakhstan', flag: '🇰🇿', airports: [{ code: 'ALA', city: 'Almaty' }] },
  { country: 'Uzbekistan', flag: '🇺🇿', airports: [{ code: 'TAS', city: 'Tashkent' }] },
  // Americas
  { country: 'USA', flag: '🇺🇸', airports: [{ code: 'JFK', city: 'New York JFK' }, { code: 'LAX', city: 'Los Angeles' }, { code: 'ORD', city: 'Chicago' }, { code: 'MIA', city: 'Miami' }, { code: 'ATL', city: 'Atlanta' }, { code: 'SFO', city: 'San Francisco' }, { code: 'DFW', city: 'Dallas' }, { code: 'LAS', city: 'Las Vegas' }] },
  { country: 'Canada', flag: '🇨🇦', airports: [{ code: 'YYZ', city: 'Toronto' }, { code: 'YVR', city: 'Vancouver' }, { code: 'YUL', city: 'Montreal' }, { code: 'YYC', city: 'Calgary' }] },
  { country: 'Mexico', flag: '🇲🇽', airports: [{ code: 'MEX', city: 'Mexico City' }, { code: 'CUN', city: 'Cancun' }, { code: 'GDL', city: 'Guadalajara' }] },
  { country: 'Brazil', flag: '🇧🇷', airports: [{ code: 'GRU', city: 'São Paulo' }, { code: 'GIG', city: 'Rio de Janeiro' }, { code: 'BSB', city: 'Brasilia' }] },
  { country: 'Argentina', flag: '🇦🇷', airports: [{ code: 'EZE', city: 'Buenos Aires' }] },
  { country: 'Chile', flag: '🇨🇱', airports: [{ code: 'SCL', city: 'Santiago' }] },
  { country: 'Colombia', flag: '🇨🇴', airports: [{ code: 'BOG', city: 'Bogota' }, { code: 'MDE', city: 'Medellin' }] },
  { country: 'Peru', flag: '🇵🇪', airports: [{ code: 'LIM', city: 'Lima' }] },
  { country: 'Venezuela', flag: '🇻🇪', airports: [{ code: 'CCS', city: 'Caracas' }] },
  { country: 'Ecuador', flag: '🇪🇨', airports: [{ code: 'UIO', city: 'Quito' }] },
  { country: 'Panama', flag: '🇵🇦', airports: [{ code: 'PTY', city: 'Panama City' }] },
  { country: 'Costa Rica', flag: '🇨🇷', airports: [{ code: 'SJO', city: 'San Jose' }] },
  { country: 'Cuba', flag: '🇨🇺', airports: [{ code: 'HAV', city: 'Havana' }] },
  { country: 'Dominican Republic', flag: '🇩🇴', airports: [{ code: 'SDQ', city: 'Santo Domingo' }, { code: 'PUJ', city: 'Punta Cana' }] },
  { country: 'Jamaica', flag: '🇯🇲', airports: [{ code: 'KIN', city: 'Kingston' }] },
  // Africa
  { country: 'South Africa', flag: '🇿🇦', airports: [{ code: 'JNB', city: 'Johannesburg' }, { code: 'CPT', city: 'Cape Town' }, { code: 'DUR', city: 'Durban' }] },
  { country: 'Nigeria', flag: '🇳🇬', airports: [{ code: 'LOS', city: 'Lagos' }, { code: 'ABV', city: 'Abuja' }] },
  { country: 'Kenya', flag: '🇰🇪', airports: [{ code: 'NBO', city: 'Nairobi' }] },
  { country: 'Ethiopia', flag: '🇪🇹', airports: [{ code: 'ADD', city: 'Addis Ababa' }] },
  { country: 'Morocco', flag: '🇲🇦', airports: [{ code: 'CMN', city: 'Casablanca' }, { code: 'RAK', city: 'Marrakech' }] },
  { country: 'Algeria', flag: '🇩🇿', airports: [{ code: 'ALG', city: 'Algiers' }] },
  { country: 'Tunisia', flag: '🇹🇳', airports: [{ code: 'TUN', city: 'Tunis' }] },
  { country: 'Libya', flag: '🇱🇾', airports: [{ code: 'TIP', city: 'Tripoli' }] },
  { country: 'Ghana', flag: '🇬🇭', airports: [{ code: 'ACC', city: 'Accra' }] },
  { country: 'Senegal', flag: '🇸🇳', airports: [{ code: 'DSS', city: 'Dakar' }] },
  { country: 'Ivory Coast', flag: '🇨🇮', airports: [{ code: 'ABJ', city: 'Abidjan' }] },
  { country: 'Tanzania', flag: '🇹🇿', airports: [{ code: 'DAR', city: 'Dar es Salaam' }] },
  { country: 'Uganda', flag: '🇺🇬', airports: [{ code: 'EBB', city: 'Entebbe' }] },
  { country: 'Zimbabwe', flag: '🇿🇼', airports: [{ code: 'HRE', city: 'Harare' }] },
  { country: 'Zambia', flag: '🇿🇲', airports: [{ code: 'LUN', city: 'Lusaka' }] },
  { country: 'Mozambique', flag: '🇲🇿', airports: [{ code: 'MPM', city: 'Maputo' }] },
  { country: 'Botswana', flag: '🇧🇼', airports: [{ code: 'GBE', city: 'Gaborone' }] },
  { country: 'Namibia', flag: '🇳🇦', airports: [{ code: 'WDH', city: 'Windhoek' }] },
  { country: 'Angola', flag: '🇦🇴', airports: [{ code: 'LAD', city: 'Luanda' }] },
  { country: 'Congo', flag: '🇨🇬', airports: [{ code: 'BZV', city: 'Brazzaville' }] },
  { country: 'Rwanda', flag: '🇷🇼', airports: [{ code: 'KGL', city: 'Kigali' }] },
  { country: 'Cameroon', flag: '🇨🇲', airports: [{ code: 'DLA', city: 'Douala' }, { code: 'NSI', city: 'Yaounde' }] },
  { country: 'Mali', flag: '🇲🇱', airports: [{ code: 'BKO', city: 'Bamako' }] },
  { country: 'Burkina Faso', flag: '🇧🇫', airports: [{ code: 'OUA', city: 'Ouagadougou' }] },
  { country: 'Niger', flag: '🇳🇪', airports: [{ code: 'NIM', city: 'Niamey' }] },
  { country: 'Chad', flag: '🇹🇩', airports: [{ code: 'NDJ', city: 'N\'Djamena' }] },
  { country: 'Sudan', flag: '🇸🇩', airports: [{ code: 'KRT', city: 'Khartoum' }] },
  { country: 'Mauritius', flag: '🇲🇺', airports: [{ code: 'MRU', city: 'Port Louis' }] },
  { country: 'Seychelles', flag: '🇸🇨', airports: [{ code: 'SEZ', city: 'Mahe' }] },
  { country: 'Madagascar', flag: '🇲🇬', airports: [{ code: 'TNR', city: 'Antananarivo' }] },
  // Oceania
  { country: 'Australia', flag: '🇦🇺', airports: [{ code: 'SYD', city: 'Sydney' }, { code: 'MEL', city: 'Melbourne' }, { code: 'BNE', city: 'Brisbane' }, { code: 'PER', city: 'Perth' }, { code: 'ADL', city: 'Adelaide' }] },
  { country: 'New Zealand', flag: '🇳🇿', airports: [{ code: 'AKL', city: 'Auckland' }, { code: 'CHC', city: 'Christchurch' }, { code: 'WLG', city: 'Wellington' }] },
  { country: 'Fiji', flag: '🇫🇯', airports: [{ code: 'NAN', city: 'Nadi' }] },
  { country: 'Papua New Guinea', flag: '🇵🇬', airports: [{ code: 'POM', city: 'Port Moresby' }] },
  { country: 'New Caledonia', flag: '🇳🇨', airports: [{ code: 'NOU', city: 'Noumea' }] },
  { country: 'French Polynesia', flag: '🇵🇫', airports: [{ code: 'PPT', city: 'Tahiti' }] },
  { country: 'Samoa', flag: '🇼🇸', airports: [{ code: 'APW', city: 'Apia' }] },
  { country: 'Tonga', flag: '🇹🇴', airports: [{ code: 'TBU', city: 'Nuku\'alofa' }] },
  { country: 'Vanuatu', flag: '🇻🇺', airports: [{ code: 'VLI', city: 'Port Vila' }] },
  { country: 'Solomon Islands', flag: '🇸🇧', airports: [{ code: 'HIR', city: 'Honiara' }] },
  // Additional European Countries
  { country: 'Iceland', flag: '🇮🇸', airports: [{ code: 'KEF', city: 'Reykjavik' }] },
  { country: 'Croatia', flag: '🇭🇷', airports: [{ code: 'ZAG', city: 'Zagreb' }, { code: 'DBV', city: 'Dubrovnik' }] },
  { country: 'Serbia', flag: '🇷🇸', airports: [{ code: 'BEG', city: 'Belgrade' }] },
  { country: 'Bulgaria', flag: '🇧🇬', airports: [{ code: 'SOF', city: 'Sofia' }] },
  { country: 'Slovenia', flag: '🇸🇮', airports: [{ code: 'LJU', city: 'Ljubljana' }] },
  { country: 'Slovakia', flag: '🇸🇰', airports: [{ code: 'BTS', city: 'Bratislava' }] },
  { country: 'Estonia', flag: '🇪🇪', airports: [{ code: 'TLL', city: 'Tallinn' }] },
  { country: 'Latvia', flag: '🇱🇻', airports: [{ code: 'RIX', city: 'Riga' }] },
  { country: 'Lithuania', flag: '🇱🇹', airports: [{ code: 'VNO', city: 'Vilnius' }] },
  { country: 'Bosnia', flag: '🇧🇦', airports: [{ code: 'SJJ', city: 'Sarajevo' }] },
  { country: 'North Macedonia', flag: '🇲🇰', airports: [{ code: 'SKP', city: 'Skopje' }] },
  { country: 'Albania', flag: '🇦🇱', airports: [{ code: 'TIA', city: 'Tirana' }] },
  { country: 'Montenegro', flag: '🇲🇪', airports: [{ code: 'TGD', city: 'Podgorica' }] },
  { country: 'Cyprus', flag: '🇨🇾', airports: [{ code: 'LCA', city: 'Larnaca' }, { code: 'PFO', city: 'Paphos' }] },
  { country: 'Malta', flag: '🇲🇹', airports: [{ code: 'MLA', city: 'Malta' }] },
  { country: 'Luxembourg', flag: '🇱🇺', airports: [{ code: 'LUX', city: 'Luxembourg' }] },
  { country: 'Belarus', flag: '🇧🇾', airports: [{ code: 'MSQ', city: 'Minsk' }] },
  { country: 'Moldova', flag: '🇲🇩', airports: [{ code: 'KIV', city: 'Chisinau' }] },
  // Additional Asian Countries
  { country: 'Mongolia', flag: '🇲🇳', airports: [{ code: 'ULN', city: 'Ulaanbaatar' }] },
  { country: 'Bhutan', flag: '🇧🇹', airports: [{ code: 'PBH', city: 'Paro' }] },
  { country: 'Maldives', flag: '🇲🇻', airports: [{ code: 'MLE', city: 'Male' }] },
  { country: 'Brunei', flag: '🇧🇳', airports: [{ code: 'BWN', city: 'Bandar Seri Begawan' }] },
  { country: 'Timor-Leste', flag: '🇹🇱', airports: [{ code: 'DIL', city: 'Dili' }] },
  { country: 'Afghanistan', flag: '🇦🇫', airports: [{ code: 'KBL', city: 'Kabul' }] },
  { country: 'Turkmenistan', flag: '🇹🇲', airports: [{ code: 'ASB', city: 'Ashgabat' }] },
  { country: 'Tajikistan', flag: '🇹🇯', airports: [{ code: 'DYU', city: 'Dushanbe' }] },
  { country: 'Kyrgyzstan', flag: '🇰🇬', airports: [{ code: 'FRU', city: 'Bishkek' }] },
  { country: 'Taiwan', flag: '🇹🇼', airports: [{ code: 'TPE', city: 'Taipei' }] },
  { country: 'Hong Kong', flag: '🇭🇰', airports: [{ code: 'HKG', city: 'Hong Kong' }] },
  { country: 'Macau', flag: '🇲🇴', airports: [{ code: 'MFM', city: 'Macau' }] },
  // Additional American Countries
  { country: 'Uruguay', flag: '🇺🇾', airports: [{ code: 'MVD', city: 'Montevideo' }] },
  { country: 'Paraguay', flag: '🇵🇾', airports: [{ code: 'ASU', city: 'Asuncion' }] },
  { country: 'Bolivia', flag: '🇧🇴', airports: [{ code: 'LPB', city: 'La Paz' }] },
  { country: 'Guatemala', flag: '🇬🇹', airports: [{ code: 'GUA', city: 'Guatemala City' }] },
  { country: 'Honduras', flag: '🇭🇳', airports: [{ code: 'SAP', city: 'San Pedro Sula' }] },
  { country: 'Nicaragua', flag: '🇳🇮', airports: [{ code: 'MGA', city: 'Managua' }] },
  { country: 'El Salvador', flag: '🇸🇻', airports: [{ code: 'SAL', city: 'San Salvador' }] },
  { country: 'Belize', flag: '🇧🇿', airports: [{ code: 'BZE', city: 'Belize City' }] },
  { country: 'Guyana', flag: '🇬🇾', airports: [{ code: 'GEO', city: 'Georgetown' }] },
  { country: 'Suriname', flag: '🇸🇷', airports: [{ code: 'PBM', city: 'Paramaribo' }] },
  { country: 'French Guiana', flag: '🇬🇫', airports: [{ code: 'CAY', city: 'Cayenne' }] },
  { country: 'Trinidad and Tobago', flag: '🇹🇹', airports: [{ code: 'POS', city: 'Port of Spain' }] },
  { country: 'Barbados', flag: '🇧🇧', airports: [{ code: 'BGI', city: 'Bridgetown' }] },
  { country: 'Bahamas', flag: '🇧🇸', airports: [{ code: 'NAS', city: 'Nassau' }] },
  { country: 'Haiti', flag: '🇭🇹', airports: [{ code: 'PAP', city: 'Port-au-Prince' }] },
  { country: 'Puerto Rico', flag: '🇵🇷', airports: [{ code: 'SJU', city: 'San Juan' }] },
  { country: 'Aruba', flag: '🇦🇼', airports: [{ code: 'AUA', city: 'Aruba' }] },
  { country: 'Curacao', flag: '🇨🇼', airports: [{ code: 'CUR', city: 'Willemstad' }] },
];